name: Test GitHub Actions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "GitHub Actions berhasil!"
          echo "Workflow terdeteksi dan bisa dijalankan."
